export const list = [
  {
    name: "Producto 1",
    size: "M",
    price: 4000,
    id: 1,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 2",
    size: "S",
    price: 3000,
    id: 2,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 3",
    size: "M",
    price: 4500,
    id: 3,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 4",
    size: "XL",
    price: 1500,
    id: 4,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 5",
    size: "L",
    price: 2500,
    id: 5,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 6",
    size: "S",
    price: 1500,
    id: 6,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 7",
    size: "XL",
    price: 2000,
    id: 7,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 8",
    size: "L",
    price: 1200,
    id: 8,
    img: "https://picsum.photos/200/300",
  },
  {
    name: "Producto 9",
    size: "S",
    price: 1500,
    id: 9,
    img: "https://picsum.photos/200/300",
  },
];
